clear
close all
clc

N  = 50000;
N1 = 1000;
N2 = N-N1+1;

nK = 20;
nKs = 10; % NK star, to generate data with

NrOfTrials = 256;

FPE_order = zeros(NrOfTrials, 1);
AIC_order = zeros(NrOfTrials, 1);
MDL_order = zeros(NrOfTrials, 1);
FPE_val = zeros(1, nK);
AIC_val = zeros(1, nK);
MDL_val = zeros(1, nK);

omega = pi*[0.90 0.70 0.50 0.30 0.10];
rho   =    [0.75 0.95 0.85 0.80 0.90];
npairs = length(omega);
roots_ = zeros(2*npairs,1); % r = [r1 r2 ... rk*],
roots_(1:npairs) = rho.*exp(1i*omega);
roots_(npairs+1:end) = conj(roots_(1:npairs));

a_ar = poly(roots_); % a_ar = [a0 a1 ... ak*], the coefficients for the all-pole transfer function
wstar = -a_ar(2:(nKs+1))'; % w* 10*1

for i=1:NrOfTrials
    
    % One realization of AR process.
    e = randn(N,1);
    y = filter(1, a_ar, e);
    
    % Order estimation loop.
    for k = 1:nK
        
        A = zeros(N1, k);

        % --------- EDIT HERE -------------------
%         k=1 -> A=y(N2-1:N-1);
%         k=2 -> A=y(N2-1:N-1)+y(N2-2:N-2);
        for j = 1:k
            A(:, j) = y(N2-j:N-j);
        end
        d = y(N2:N);
%         w3 = inv(A' * A) * A' * d;
%         sigma = d - A * w3;
        w = A \ d;
        sigma = d - A * w;
%         [~, E] = aryule(y(N2:N), k); % Final prediction error E
        
        % For small N the performance of AIC and MDL is similar
        FPE_val(k) = var(sigma) * (N1 + k) / (N1 - k); % Final prediction error tends to underestimate the order
        AIC_val(k) = N1 * log(var(sigma)) + 2 * k; % Akaike Information Criterion tends to overestimate the order
        MDL_val(k) = N1 * log(var(sigma)) + k * log(N1); % Minimum Description Length estimates correctly the order
        
        % ---------------------------------------
    end
    
    % What is done here? 
    % Find the min value(best/desired/balanced result), take its index(nK, how many elements of data are used)
    [~,FPE_order(i)] = min( FPE_val );
    [~,AIC_order(i)] = min( AIC_val );
    [~,MDL_order(i)] = min( MDL_val );
    
end

% Plot results. What is shown? Explain the results.
% looped 256 times, most of them get best(minimun) result when k=10 (10 columns of data in A)
% Noisy -> Best/suitable/desired -> Distorion?
figure(1);
subplot(311)
hist(FPE_order,(1:nK));
title('FPE criterion','Fontsize',12);
xlabel('order k^*','Fontsize',12);
ylabel('Trials','Fontsize',12);

subplot(312)
hist(AIC_order,(1:nK));
title('AIC criterion','Fontsize',12);
xlabel('order k^*','Fontsize',12);
ylabel('Trials','Fontsize',12);

subplot(313)
hist(MDL_order,(1:nK));
title('MDL criterion','Fontsize',12);
xlabel('order k^*','Fontsize',12);
ylabel('Trials','Fontsize',12);


% What do the plots represent?
% 10 columns of data in A can bring up the best desired result
% Can you see the actual model order from the definition of our AR process?
% roots_ is 10*1 and y is generated by a_ar, a_ar is generated by roots_


